server:
  port: 8083

spring:
  batch:
    initialize-schema: always
  application:
    name: etl-process

##------EUREKA---------##
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

##------DB---------##
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/data-db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect