server:
  port: 8080

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  application:
    name: client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
